about/urls.py
from django.urls import path
from .views import *

app_name = 'about'

urlpatterns = [
    path('', about, name='about'),
]

homepage/urls.py
from django.urls import path
from .views import *

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('add_status/', add_status, name='add_status'),

]

story10/urls.py
from django.urls import path
from .views import *

app_name = 'story10'

urlpatterns = [
    path('', index, name='index'),
]

story6/urls.py
from django.conf.urls import include
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story10.urls')),
    path('story6/', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story8/urls.py
from django.urls import path
from .views import *

app_name = 'story8'

urlpatterns = [
    path('', books, name='books'),
]

story9/urls.py
from django.urls import path,include
from .views import *

app_name = 'story9'

urlpatterns = [
    path('signup/', regist, name='regist'),
    path('', include('django.contrib.auth.urls'))

]

about/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
import datetime

class Status(models.Model):
	dates = models.DateTimeField(auto_now_add=True)
	status = models.TextField(max_length=300)
	
	

story10/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
	class Meta:
		model= Status
		fields = ['status']
		labels = {
			'status' : 'Status'}
		widgets = {
			'status' : forms.Textarea(attrs={'class': 'form-control',
										'type' : 'text',
										'placeholder' : 'Apa yang kamu rasakan hari ini?'}),
		}

about/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import StatusForm
from .models import Status
from datetime import datetime, date

def index(request):
    data = Status.objects.all()
    form = StatusForm()

    content = {'title' : 'Status',
                'form' : form,
                'text' : 'Halo, apa kabar?',
                'data' : data}
    return render(request, 'landingpage.html', content)
def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:index')

story10/views.py
from django.shortcuts import render

def index(request):

    host = request.get_host()
    port = request.get_port()

    context = {
        'host':host,
        'port':port,
    }

    return render(request, 'index.html', context)

story8/views.py
from django.shortcuts import render

def books(request):
    return render(request, 'listbuku.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def regist(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect('homepage:index')
	else:
		form = UserCreationForm()

	return render(request, 'regist.html', {'form': form})

about/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About Me {% endblock %}



{% block content %}

<br><br><br><br>
<h1>About Me</h1>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<img src="{% static 'about/img/profil.png' %}">
		</div>
		<div class="col-md-6" id="accordion">
			<h3 id="header-accordion">My Activity </h3>
			<div class="panel">
				<ul>
					<li>Kuliah</li>
					<li>Rapat Organisasi</li>
					<li>Nugas</li>
					<li>Makan</li>
					<li>Tidur</li>
				</ul>
			</div>
		  	<h3 id="header-accordion">Organizations & Committees Experience</h3>
		  	<div class="panel">
		    	<p><b>Staf Muslimah Center FUKI Fasilkom UI</b></p>
		    	<p>Februari 2019 - Sekarang</p>
		    	<p><b>Wakil Penanggung Jawab Akomodasi SIWAK-NG 2019</b></p>
		    	<p>Februari 2019 - November 2019</p>
		    	<p><b>Staf Divisi Data Science Academy COMPFEST 11</b></p>
		    	<p>Februari 2019 - September 2019</p>
		    	<p><b>Wakil Penanggung Jawab Divisi Konsumsi Wisuda Genap 2019 Fasilkom UI</b></p>
		    	<p>Februari 2019 - Agustus 2019</p>
		    	<p><b>Staf Divisi Konsumsi Wisuda Ganjil 2019 Fasilkom UI</b></p>
		    	<p>Desember 2018 - Januari 2019</p>
		  </div>
		  
		  <h3 id="header-accordion">Achievements</h3>
		  <div class="panel">
		  	<ul>
		  		<li>Semifinalis National Business Case Competition Universitas Airlangga</li>
		  		<li>Top 5 UI/UX Competition Ristek Fasilkom UI</li>
		  		<li>Penerima Beasiswa Mobile Progresive Web Application Dicoding IDCamp</li>
		  	</ul>
		  </div>
		</div>
	</div>
</div>  
{% endblock %}

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tentang Saya</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'homepage/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{%static 'about/js/script.js' %}"></script>
    {% block scripts %} {% endblock %}
    

</head>
<body id="page-top">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
      
            <div class="collapse navbar-collapse justify-content-center " id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'about:about' %}">About</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'story8:books' %}">List Buku</a>
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'story9:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'story9:login' %}">Login</a>
                        {% endif %}
                    </li>
                    <li>
                        <button id="theme" class="btn btn-primary waves-effect waves-light" style="margin-top: 10px;">
                            <h4>Neon Theme</h4>
                        </button>
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    </header>
    
    {% block content %} {% endblock %}

    
    
</body>
</html>

homepage/templates/landingpage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Daftar Status {% endblock %}



{% block content %}
    <br><br><br><br>
    <h1 id="salam">{{text}}</h1>
    <h1>Selamat Datang {{request.user.username}}</h1>
    <form id="form" class="left" style="width: 50%; margin: 0 auto" method="POST" action="{% url 'homepage:add_status' %}" novah4date>
        {% csrf_token %}
        <div class="form-group center">
            <label for="status"><strong>{{ form.status.label_tag }}</strong></label>
                {{ form.status }}
        </div>
        <br>
        <button id="submit" type="submit" class="btn btn-primary waves-effect waves-h4ght" value="Save"><h4>Add</h4></button>
    </form>
    <hr>
    


    <hr>
	<div class="col-md-12">
        {% if data %}
        <h1 id="list">Daftar Status</h1>
            {% for obj in data %}
            <div class="col-md center">
                <h5>{{ obj.dates }}</h5>
                <h4>{{ obj.status }}</h4>
                <hr>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    <hr>
{% endblock %}

story10/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 10 {% endblock %}



{% block content %}
<br><br><br><br>
	<h1>Hello World!</h1>
	<div class="container">
		<h2>
	        This website is served by:  <br>
	        HOST: {{ host }}            <br>
	        PORT: {{ port }}            
	    </h2>
	</div>
    
{% endblock %}

story8/templates/listbuku.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Story 8 - Anatasya Dwijayanti</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{%static 'css/style.css' %}">

</head>
<body>
	<br><br>
	<h1>Book Finder</h1>
	<div class="container">
		<input id="search" placeholder="Title or Author">
		<button id="button" type="button">Search</button>
	</div>
	<br>
	<div id="results" class="col-md-12 left">
		<table  class="table m-0">
				<thead>
					<tr>
						<th>Cover Buku</th>
						<th>Title</th>
						<th>Author</th>
					</tr>
				</thead>
				<tbody id="listbook">
				</tbody>
			</table>
		
	</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{%static 'js/script.js' %}"></script>

</body>
</html>

story9/templates/regist.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register {% endblock %}

{% block content %}
	<br><br><br><br>
	<div class="container">
		<h2>Daftar</h2>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit" name="button">Daftar</button>
		</form>
	</div>
	
{% endblock %}